docs_dir: src
site_name: Landspatientregisteret 3 - Technical documentation
pages:
- Home: index.md
- Definitions: definitions.md
- Governace: governance.md
- Documentation:
  - Interface aspects and usage: aspects.md
  - Submission scheme: submission-scheme.md
- Interfaces:
  - XDR: interface/xdr.md
  - Accumulated error list: interface/accumulated-error-list.md
- Test environment: testenvironment.md
- Development resources: developmentresources.md
- Examples: examples.md
- FAQ: faq.md  
- Related material and links: links.md
#- LPR 2 specifik dokumentation:
theme: readthedocs

repo_url: https://github.com/scandihealth/lpr3-docs/
edit_uri: edit/master/src

use_directory_urls: false
markdown_extensions: [fenced_code]
extra_css:
  - css/highlight.js/idea.css
  - css/theme-overrides.css